#!/bin/bash -xe
sed -i '/^deb http:/ s/$/ contrib non-free/' /etc/apt/sources.list
echo "deb [trusted=yes] file://$DEPSBASE ./" >> /etc/apt/sources.list
echo "deb [arch=arm64] http://packages.cloud.google.com/apt mendel-bsp-$BOARD_NAME-day main" >> /etc/apt/sources.list
echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" >> /etc/apt/sources.list
echo 'Debug::pkgProblemResolver true;' > /etc/apt/apt.conf
cp -r ${ROOTDIR}/build/lintian /usr/share/
cat ${ROOTDIR}/build/bazel-release.pub.gpg | apt-key add -
cat ${ROOTDIR}/packages/mendel-keyring/cloud-key.gpg | apt-key add -
cat ${ROOTDIR}/packages/mendel-keyring/linux_signing_key.pub |apt-key add -
apt-get update || true
