#!/bin/bash -xe
sed -i '/^deb http:/ s/$/ contrib non-free/' /etc/apt/sources.list
echo "deb [trusted=yes] file://$DEPSBASE ./" >> /etc/apt/sources.list
echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" >> /etc/apt/sources.list
echo 'Debug::pkgProblemResolver true;' > /etc/apt/apt.conf
cp -r /rootdir/build/lintian /usr/share/
cat /rootdir/build/bazel-release.pub.gpg | apt-key add -
apt-get update
