#!/bin/bash -xe
sed -i '/^deb http:/ s/$/ contrib non-free/' /etc/apt/sources.list
echo "deb [trusted=yes] file://$DEPSBASE ./" >> /etc/apt/sources.list
echo "deb [arch=arm64] http://packages.cloud.google.com/apt mendel-bsp-$BOARD_NAME-day main" >> /etc/apt/sources.list
echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" >> /etc/apt/sources.list
echo 'Debug::pkgProblemResolver true;' > /etc/apt/apt.conf

install -D -m 644 -o root -g root \
        ${ROOTDIR}/build/lintian/profiles/mendel/main.profile \
              /usr/share/lintian/profiles/mendel/main.profile
install -D -m 644 -o root -g root \
        ${ROOTDIR}/build/lintian/vendors/mendel/main/data/changes-file/known-dists \
              /usr/share/lintian/vendors/mendel/main/data/changes-file/known-dists

cat ${ROOTDIR}/build/bazel-release.pub.gpg | apt-key add -
cat ${ROOTDIR}/packages/mendel-keyring/cloud-key.gpg | apt-key add -
cat ${ROOTDIR}/packages/mendel-keyring/linux_signing_key.pub |apt-key add -
apt-get update || true
